/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuatroenlinea.View;

/**
 *
 * @author agust
 */
public class CreateNewPlayerView extends javax.swing.JFrame {

  /**
   * Creates new form CreateNewPlayerView
   */
  public CreateNewPlayerView() {
    initComponents();
  }

  public javax.swing.JTextField getCreateNewPlayerTextField() {
    return createNewPlayerTextField;
  }

  public javax.swing.JButton getCreateNewPlayerSubmitButton() {
    return createNewPlayerSubmitButton;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jPanel1 = new javax.swing.JPanel();
    createNewPlayerTextField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    createNewPlayerSubmitButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
    jLabel1.setText("Crear un nuevo jugador");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    jLabel2.setText("Nombre");

    createNewPlayerSubmitButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    createNewPlayerSubmitButton.setText("Crear");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap(554, Short.MAX_VALUE)
            .addComponent(
              jLabel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              437,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(535, 535, 535)
        )
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGap(569, 569, 569)
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel2)
                        .addComponent(
                          createNewPlayerTextField,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          375,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGap(662, 662, 662)
                    .addComponent(
                      createNewPlayerSubmitButton,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      184,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanel1Layout
            .createSequentialGroup()
            .addGap(45, 45, 45)
            .addComponent(
              jLabel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              78,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              222,
              Short.MAX_VALUE
            )
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              createNewPlayerTextField,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              87,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(111, 111, 111)
            .addComponent(
              createNewPlayerSubmitButton,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              60,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(78, 78, 78)
        )
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton createNewPlayerSubmitButton;

  private javax.swing.JTextField createNewPlayerTextField;

  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
